=== SantiagoLuqueVillanueva/ejercicioldm_ej09/catalogo.dtd
<!ELEMENT catalogo (libro+)>
<!ELEMENT libro (titulo,autor?,ano,creador?)>
<!ATTLIST libro id NMTOKEN #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT creador (#PCDATA)>

=== SantiagoLuqueVillanueva/ejercicioldm_ej09/ejercicio9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">

<catalogo>
    <libro id=”1”>
	<libro:titulo>Harry Potter y la piedra filosofal</libro:titulo>
	<libro:autor>J.K. Rowling</libro:autor>
	<libro:ano>1997</libro:ano>
    </libro>
    
    <libro id=”2”>
	<dc:titulo>Don Quijote de la mancha</dc:titulo>
	<dc:creador>Miguel de Cervantes</dc:creador>
	<dc:ano>1605</dc:ano>
    </libro>
</catalogo>
